name: CustomText
version: 1.0
main: net.cyberflame.customtext.CustomText
author: CyberFlame, Sulphate

commands:
  customtext:
    description: Lists or modifies existing CustomText commands.
    usage: /<command> <list/add/delete/reload> [command-name] [..lines]
    aliases: [ ctext, ct ]

permissions:
  customtext.admin:
    default: op